-- seed.sql
INSERT INTO wines (name, description, price, year, type) VALUES
('Chardonnay', 'A popular white wine with a wide flavor range from buttered to unoaked.', 20.99, 2018, 'white'),
('Sauvignon Blanc', 'Crisp, elegant, and fresh, with a hint of green apples.', 18.50, 2019, 'white'),
('Pinot Grigio', 'Light and crisp, often with notes of lemon and pear.', 15.99, 2018, 'white'),
('Riesling', 'Often sweet and fruity, with high acidity and floral tones.', 22.00, 2020, 'white'),
('Moscato', 'Sweet and lightly sparkling with hints of peach and orange blossom.', 16.50, 2019, 'white'),
('Viognier', 'Full-bodied white wine with floral aromas and peach flavors.', 21.25, 2017, 'white'),
('Gewürztraminer', 'Aromatic wine with notes of tropical fruits and a spicy finish.', 19.90, 2016, 'white'),
('Chenin Blanc', 'Versatile wine ranging from dry to sweet, with honeyed flavors.', 17.85, 2018, 'white'),
('Semillon', 'Medium to full-bodied wine, often with hints of lemon and mineral.', 23.45, 2019, 'white'),
('Albariño', 'A dry, light-bodied wine with aromas of citrus and flowers.', 25.00, 2020, 'white'),

('Cabernet Sauvignon', 'A red wine known for its depth of flavor, commonly aged in oak barrels.', 35.50, 2016, 'red'),
('Merlot', 'Soft, ripe, elegant with a plummy fruit flavor and a velvety feel.', 30.25, 2018, 'red'),
('Pinot Noir', 'A red wine that is light-bodied and fruity, perfect for any occasion.', 22.75, 2019, 'red'),
('Syrah', 'Rich and robust with flavors of blackberry, plum, and black pepper.', 27.50, 2017, 'red'),
('Zinfandel', 'Fruity yet spicy with a robust alcohol content.', 29.90, 2015, 'red'),
('Malbec', 'Dark, full-bodied, and rich with berry flavors and a smoky finish.', 24.99, 2019, 'red'),
('Sangiovese', 'Medium-bodied red with notes of cherry and earthy spices.', 26.45, 2018, 'red'),
('Barbera', 'Italian red with high acidity and flavors of dark cherry and dried herbs.', 20.85, 2017, 'red'),
('Amarone', 'Rich Italian wine, with a strong raisin flavor due to the drying of grapes.', 50.00, 2015, 'red'),
('Grenache', 'Soft on the palate with red fruit flavors and a hint of spice.', 25.30, 2016, 'red'),

('Provence Rosé', 'Classic rosé with delicate flavors of strawberry, rose petals, and herbs.', 24.75, 2019, 'rosé'),
('White Zinfandel', 'Light and fruity rosé with a slightly sweet profile.', 15.00, 2018, 'rosé'),
('Pinot Noir Rosé', 'Elegant, crisp rosé with flavors of ripe berries and a hint of melon.', 22.50, 2020, 'rosé'),
('Tempranillo Rosé', 'Vibrant and savory with notes of cherry, spice, and floral undertones.', 18.99, 2019, 'rosé'),
('Sangiovese Rosé', 'Italian rosé with fresh and fruity characteristics, crisp and dry.', 20.00, 2018, 'rosé'),
('Cabernet Sauvignon Rosé', 'Rosé with a rich, full-bodied profile and notes of raspberry and cherry.', 19.95, 2019, 'rosé'),
('Syrah Rosé', 'Full-flavored with vibrant berry and plum flavors balanced by a sharp spice.', 21.85, 2017, 'rosé'),
('Merlot Rosé', 'Soft and medium-bodied with a pleasant mix of berries and citrus.', 16.45, 2020, 'rosé'),
('Grenache Rosé', 'Light and refreshing with a palate of red fruit and hints of orange zest.', 23.55, 2020, 'rosé'),
('Cinsault Rosé', 'Dry and aromatic, perfect for a sunny day, with notes of raspberry and cherry.', 22.10, 2019, 'rosé');
